 Vagrant.configure(2) do |config|
 
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/trusty64"
    ubuntu.vm.network :forwarded_port, guest: 22, host: 12202, id: 'ssh'
    ubuntu.vm.network "private_network", virtualbox__intnet: "management",
                                      ip: "10.0.1.1/24", auto_config: true
    ubuntu.vm.provider :virtualbox do |vb|
      vb.gui = false
      vb.memory = "2048"
    end 
    ubuntu.vm.provision "file", source: "ansible.cfg", destination: "ansible.cfg" 
    ubuntu.vm.provision "file", source: "provision", destination: "provision"
    #ubuntu.vm.provision "file", source: "data/template.j2", destination: "/tmp/template.j2"
    ubuntu.vm.provision "shell", inline: <<-SHELL
     #mkdir dir1
     #touch dir1/file1
     sudo apt-get update
     sudo apt-get install -y python-dev libxml2-dev python-pip libxslt-dev build-essential libssl-dev libffi-dev libffi-dev
     sudo pip install --upgrade setuptools
     sudo pip install cryptography==1.2.1 junos-eznc ansible==2.4.2.0 jxmlease
     sudo ansible-galaxy --force install Juniper.junos,1.4.3
    SHELL
    ubuntu.vm.synced_folder "synced_folder", "/home/vagrant/scripts"  
    ubuntu.ssh.username = "vagrant"
    ubuntu.ssh.password = "vagrant"
  end
 
  config.vm.define "vsrx01" do |vsrx01|
    vsrx01.vm.box = "juniper/ffp-12.1X47-D20.7-packetmode"  
    vsrx01.vm.network :forwarded_port, guest: 22, host: 12233, id: 'ssh'
    vsrx01.vm.network "private_network", virtualbox__intnet: "management",
                      ip: "10.0.1.10",
                      netmask: "255.255.255.0"
  end

end
